[project]
name = "grimstad-courses-wiki"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hx", email = "hx@datapor.no" }
]
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.7",
    "pymdown-extensions>=12.1",
]

